/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,jsx,mdx}",
    "./src/components/**/*.{js,jsx,mdx}",
    "./src/app/**/*.{js,jsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#f0f1f1",
        "secondary-container": "#fe851e",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#474747",
        "surface": "#f9f9f9",
        "on-secondary-fixed-variant": "#723600",
        "surface-container": "#eeeeee",
        "on-primary": "#ffffff",
        "primary": "#000000",
        "on-secondary-fixed": "#311300",
        "on-tertiary-fixed": "#001e2f",
        "surface-container-low": "#f3f3f4",
        "tertiary": "#000000",
        "outline": "#7e7576",
        "inverse-primary": "#c6c6c6",
        "on-tertiary-fixed-variant": "#004c6e",
        "surface-tint": "#5e5e5e",
        "on-background": "#1a1c1c",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#848484",
        "tertiary-fixed-dim": "#88ceff",
        "outline-variant": "#cfc4c5",
        "tertiary-fixed": "#c8e6ff",
        "on-surface": "#1a1c1c",
        "on-tertiary-container": "#008cc7",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#c6c6c6",
        "on-secondary": "#ffffff",
        "tertiary-container": "#001e2f",
        "secondary-fixed-dim": "#ffb786",
        "surface-container-highest": "#e2e2e2",
        "background": "#f9f9f9",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#1b1b1b",
        "secondary-fixed": "#ffdcc6",
        "surface-container-high": "#e8e8e8",
        "on-secondary-container": "#612d00",
        "surface-bright": "#f9f9f9",
        "inverse-surface": "#2f3131",
        "surface-variant": "#e2e2e2",
        "secondary": "#964900",
        "on-surface-variant": "#4c4546",
        "surface-dim": "#dadada",
        "primary-fixed": "#e2e2e2",
        "primary-container": "#1b1b1b",
        "accent-blue": "#03b5ff",
        "accent-purple": "#730697",
        "accent-orange": "#f57f15",
        "editor-bg": "#1e1e1e"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        md: "16px",
        lg: "24px",
        gutter: "24px",
        base: "4px",
        xl: "48px",
        "margin-desktop": "48px",
        sm: "8px",
        xs: "4px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        display: ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        code: ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"]
      }
    }
  },
  plugins: [],
};